version: '2'
networks:
  default:
    external:
      name: aaa
services:
    mongo-1-2:
        container_name: "mongo-1-2"
        image: mongo
        volumes:
            - ./${MONGO_1_2_SAVE_PATH}:/data/db
        ports:
            - "30012:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles 
        restart: always

    mongo-1-3:
        container_name: "mongo-1-3"
        image: mongo
        volumes:
            - ./${MONGO_1_3_SAVE_PATH}:/data/db
        ports:
            - "30013:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles 
        restart: always 

    mongo-1-1:
        container_name: "mongo-1-1"
        image: mongo
        volumes:
            - ./${MONGO_1_1_SAVE_PATH}:/data/db
        ports:
            - "30011:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles 
        links:
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
        restart: always
